### ISSUE TITLE
Is roboneuro down?

### ISSUE THREAD

**Issue by arokem** [neurolibre/template#7]
<img width="1624" alt="Screenshot 2024-10-15 at 10 26 40 AM" src="https://github.com/user-attachments/assets/5b37845d-ae38-4af0-9c7d-942706eadccb">

**Comment by emdupre** [comment]
The roboneuro-neo app (with an updated stack) is currently live : https://roboneuro-neo.herokuapp.com/

I believe this is intended to replace the current roboneuro app (with a legacy stack), which looks like it's officially hit EOL. @agahkarakuzu  can confirm, though !

**Comment by agahkarakuzu** [comment]
The dyno on the old one was shut down, but will double check. New deployments are from -neo suffixed repos, old sources are archived. 

https://robo.neurolibre.org is the domain registered addr for the new app.

**Comment by arokem** [comment]
I submitted my repo through the new link and got a couple of messages per email. The last 
message (two days ago) read: 

<img width="1030" alt="Screenshot 2024-10-17 at 7 58 50 AM" src="https://github.com/user-attachments/assets/e576cb5b-ce52-4e8e-97a3-6cb25967695a">

Is it normal for the next stage of this to take days?

**Comment by agahkarakuzu** [comment]
@arokem the background task that handles requests through the robo.neurolibre.org page requires some update. I'll try to get to it asap and will let you know.

**Comment by agahkarakuzu** [comment]
In the meantime, you can visit

https://binder-preview.conp.cloud

to build an image. 

The new submission convention now applies a completely different strategy to build books & handle data. The documentation will be updated to reflect this soon.

**Comment by arokem** [comment]
Great. Thanks!

**Comment by arokem** [comment]
Step 1 on that page ("data requirement?") is currently broken because it points to a link that is no longer valid (https://github.com/neurolibre/neurolibre/issues/new?assignees=&labels=data+requirement&template=data-requirement.md&title=%5BData+Requirement%5D), as that repository has been archived and new issues cannot be created on it.

**Comment by arokem** [comment]
How should I handle data requirements for now? Where is the format of the `data_requirement.json` file documented?

**Comment by agahkarakuzu** [comment]
Hi @arokem, thank you for catching this! There is a mistake in the URL that I'll fix, it should be:

https://github.com/neurolibre/info/issues/new?assignees=&labels=data+requirement&template=data-requirement.md&title=%5BData+Requirement%5D

**Comment by arokem** [comment]
Thanks! I will post the issue with some details about the data we have in mind. 

Also, I am running into some issues spinning up a binder instance on the neurolibre binder server: 

<img width="1624" alt="Screenshot 2024-10-28 at 1 53 44 PM" src="https://github.com/user-attachments/assets/5ce6e0c2-a1cb-44ee-b655-dfcf8728b850">

Do you know why that's happening?

**Comment by agahkarakuzu** [comment]
Interesting, I accessed from an ocean apart (Turkey), and it opened in a matter of seconds (both on Brave and Chrome):

<img width="1195" alt="image" src="https://github.com/user-attachments/assets/93864310-dbc8-4a05-9542-20f4eaf91f17">

Are you accessing from a lab computer? I found [this](https://discourse.jupyter.org/t/error-in-event-stream-typeerror-failed-to-fetch-when-launching-a-binder/26574/13) issue that looked similarly mystifying. I just checked the server and it is not overloaded with requests...

**Comment by arokem** [comment]
Oh - looks like it's working for me now! If this issue was still open it, I suppose I would have closed it 😁
